### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by LittleCodingFox** [MQuy/mos#1]
Is there a license to this OS? I'd love to contribute while making my own changes.

Thank you.

**Comment by MQuy** [comment]
thank @LittleCodingFox, it is under MIT License :)

**Comment by LittleCodingFox** [comment]
Could you add a LICENSE file with the license copy/paste? Would be great :)

**Comment by MQuy** [comment]
just updated 👍🏻
> without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense

**Comment by LittleCodingFox** [comment]
Awesome, thanks!
