### ISSUE TITLE
Build says mos.bin is not multiboot

### ISSUE THREAD

**Issue by samuelh2005** [MQuy/mos#14]

**Comment by samuelh2005** [comment]
Which then, it seems to make this check in the kernel main fail
```c
int kernel_main(uint32_t addr, uint32_t magic)
{
	if (magic != MULTIBOOT2_BOOTLOADER_MAGIC)
		return -1;
```
because grub probably passes the non multi-boot magic in and then the kernel seems to hang

**Comment by samuelh2005** [comment]
@MQuy Hello? Do you have any ideas? I even reinstalled the i386-elf-grub tools

**Comment by MQuy** [comment]
The last time I tried for both MacOS and Ubuntu, it is working. Which OS are you using, my guess could be you are using old grub version or newest grub version which I haven't tested

**Comment by samuelh2005** [comment]
Mac Os, thank you for helping!

**Comment by samuelh2005** [comment]
My GRUB version is 2.11

**Comment by MQuy** [comment]
I just tested, it doesn't work with latest MacOS Big Sur. Sorry to say this but I don't think we can compile this repo in MacOS Big Sur, I would suggest to switch to Linux since it is easier to do os dev. Just in case, I haven't tested this formula yet https://github.com/nativeos/homebrew-i386-elf-toolchain, it seems support older grub version :).

**Comment by samuelh2005** [comment]
I will try them first, thanks!

**Comment by samuelh2005** [comment]
Everything I do still seems not to work :( . Can you provide a docker image that can be used to build?

**Comment by ghost** [comment]
> Mac Os, thank you for helping!

That's your issue. You're on a Mac.

**Comment by ghost** [comment]
> Everything I do still seems not to work :( . Can you provide a docker image that can be used to build?

Good God dude... You seem like you have no idea what your doing. I'd advice you stick to simple userspace projects.

**Comment by samuelh2005** [comment]
I might as well just close this now. I should closed this ages ago.
