### ISSUE TITLE
Free alternatives for " hdiutil: attach failed - no mountable file system "

### ISSUE THREAD

**Issue by ajh123** [MQuy/mos#2]
Hello i am running mac os Catalina and would want to. compile your OS ,i tried a few alternatives and couldn't get them to work with your scripts, maybe you could? And i don't want to use [this](https://www.paragon-software.com/home/extfs-mac/) because i seen its a trail and have to pay afterwards, or i might be missing something.

**Comment by MQuy** [comment]
hi @ajh123, thank for your question. macos doesn't support ext2 well so we need extfs-mac to support it. I haven't found any better than way than
- install extfs-mac with 30-trial
- using prebuilt `hdd.iso` which I can upload it for you, so you don't need to run `./create_image.sh`, only `./build qemu iso` is ok to run

**Comment by ajh123** [comment]
thx!

**Comment by ajh123** [comment]
@MQuy 
we could set up a ubuntu vagrant machine in the project's root so when we go on the vm our project will be mounted at /vagrant/ so we can run the build scrips on there, then on the host (mac os) run qemu or whatever

**Comment by ajh123** [comment]
@MQuy i can set up the vagrant machine in a fork, and we can merge to help others

**Comment by MQuy** [comment]
thank @ajh123 👍
