### ISSUE TITLE
Installing MOS in linux 20.04 Focal Fossa

### ISSUE THREAD

**Issue by parth-27** [MQuy/mos#3]
I am facing issues during Installation of MOS in Ubuntu 20.04 due to some different commands of shell script in Mac and Linux in creater_image.sh and build.sh
We are unable to make ISO file. 
So can you please provide alternative linux commands for building ISO file

**Comment by MQuy** [comment]
hi @parth-27, mOS is developed in macOS so unfortunately, script is made for macOS.
I tested in linux few months ago, I reused `hdd.iso` (which was generated from `create_image.sh` in my macOS) and modified `build,sh` and `kernel/Makefile` like this commit https://github.com/MQuy/mos/commit/1ea2517e30fa7755df3a106f53167e6af81b221b#diff-56e96dd96a04965bc16ae7b79379ff8e
I think the fast way is I can upload `hdd.iso` so you can reuse it, and modify other build scripts like above?

**Comment by parth-27** [comment]
> hi @parth-27, mOS is developed in macOS so unfortunately, script is made for macOS.
> I tested in linux few months ago, I reused `hdd.iso` (which was generated from `create_image.sh` in my macOS) and modified `build,sh` and `kernel/Makefile` like this commit [1ea2517#diff-56e96dd96a04965bc16ae7b79379ff8e](https://github.com/MQuy/mos/commit/1ea2517e30fa7755df3a106f53167e6af81b221b#diff-56e96dd96a04965bc16ae7b79379ff8e)
> I think the fast way is I can upload `hdd.iso` so you can reuse it, and modify other build scripts like above?

Yess, Can you please Upload it, it would be very helpful

**Comment by MQuy** [comment]
I created new branch `ubuntu`, already tested in my ubuntu 20. Let me know if everything is not working

**Comment by parth-27** [comment]
![issue](https://user-images.githubusercontent.com/54990846/94999409-d20ade80-05d6-11eb-9dbd-90a014b57263.jpeg)

Hi, we tried to run ./build.sh qemu iso and we got this error, can you please tell us what's wrong?

**Comment by MQuy** [comment]
the error said that `i686-elf-gcc` is not found, could you try to install it?

**Comment by parth-27** [comment]
Yes, i installed i686-elf-gcc and tried running the OS

**Comment by MQuy** [comment]
did you run `make install` when installing `i686-elf-gcc`, can you check your PATH to make sure it contains folder which contains `i686-elf-gcc`

**Comment by Mithilesh1609** [comment]
Hi, I have tried to install mos in ubuntu-20..04, but i am getting error like this.
![Screenshot from 2020-10-05 22-34-46](https://user-images.githubusercontent.com/43612001/95110053-14f5bf00-075b-11eb-84f2-3646e584751c.png)

**Comment by MQuy** [comment]
hi @Mithilesh1609, I don't think you can run brew in ubuntu, I will improve the README for ubuntu setup

**Comment by manasvi89** [comment]
![Screenshot from 2020-10-08 14-17-35](https://user-images.githubusercontent.com/41832733/95436229-3b8d4300-0971-11eb-9b02-231c331eaa24.png)
![Screenshot from 2020-10-08 14-18-25](https://user-images.githubusercontent.com/41832733/95436247-4051f700-0971-11eb-915b-89773b26d84f.png)

We have followed all the steps for installation and we are trying to boot iso file in qemu but We are getting an error.

**Comment by MQuy** [comment]
@manasvi89 did you checkout ubuntu branch and run `./build qemu iso`?

**Comment by manasvi89** [comment]
Yes I did that and now I am getting an error about missing mos.bin file.
![Screenshot from 2020-10-08 20-59-13](https://user-images.githubusercontent.com/41832733/95480194-406de900-09a9-11eb-98ea-9ec2b62413e6.png)

**Comment by MQuy** [comment]
can you screenshot this `cd src/kernel && make clean && make`?

**Comment by manasvi89** [comment]
Yes.Here, It is
![Screenshot from 2020-10-08 21-04-03](https://user-images.githubusercontent.com/41832733/95480735-de61b380-09a9-11eb-9559-f3b36505c79c.png)

**Comment by MQuy** [comment]
you shouldn't use brew in linux, follow the guide here from `The build` https://wiki.osdev.org/GCC_Cross-Compiler

**Comment by manasvi89** [comment]
Ok Thank You
