### ISSUE TITLE
mOS in Ubuntu 

### ISSUE THREAD

**Issue by sxmxr** [MQuy/mos#5]
Hi @MQuy, I and my teammates have successfully installed GCC Cross-complier using that Wikipedia page which was mentioned in one of the earlier issues. (https://wiki.osdev.org/GCC_Cross-Compiler) I have installed i686-elf-gcc successfully(Screenshot-1) Now while installing the whole project, using the mentioned shell scripts in the read.me, I got error like, "./create_image.sh: line 6: hdiutil: command not found".(Screenshot 2). My host OS is Windows 10 and I'm using Ubuntu 20.04 within the virtual box.
![Screenshot from 2020-10-21 15-15-24](https://user-images.githubusercontent.com/47913479/97078955-cf1b7080-160d-11eb-9367-b7b2acb7fd19.png)
![Screenshot from 2020-10-24 15-31-48](https://user-images.githubusercontent.com/47913479/97078998-0c7ffe00-160e-11eb-989e-c2446e033127.png)

**Comment by MQuy** [comment]
@sxmxr if you check out master branch and run like this I think it will work
```
$ cd src
$ ./create_image.sh
$ ./build qemu iso
```

**Comment by sxmxr** [comment]
@MQuy Thank you for your reply. I have tried it but it still shows this error. After searching about it, that command is used in mac and there's a separate command for Ubuntu(https://askubuntu.com/questions/412958/hdiutil-command-not-found). Do we need to change create_image.sh file according to Ubuntu commands?

**Comment by sxmxr** [comment]
> @MQuy Thank you for your reply. I have tried it but it still shows this error. After searching about it, that command is used in mac and there's a separate command for Ubuntu(https://askubuntu.com/questions/412958/hdiutil-command-not-found). Do we need to change create_image.sh file according to Ubuntu commands?

@MQuy I have changed "hdiutil" with "ccd2iso" and successfully ran ./create_image.sh file. Now 1 more error occurred while running "./build.sh qemu iso" like:
![Screenshot from 2020-10-24 16-01-21](https://user-images.githubusercontent.com/47913479/97079528-43581300-1612-11eb-8604-829eda4c4dd1.png)

**Comment by MQuy** [comment]
you shouldn't need to change anything, I changed `create_image.sh` to support ubuntu if you pull master. 
### To build toolchain
```
$ cd src
$ cd toolchain && ./build.sh
```
### Run
```
$ cd src
$ ./create_image.sh
$ ./build.sh qemu iso
```

**Comment by sxmxr** [comment]
@MQuy Thank you for your response. ./create_image.sh was compiled successfully but while running "./build qemu iso" command I'm getting this error.
![Screenshot from 2020-10-24 16-17-28](https://user-images.githubusercontent.com/47913479/97079866-bf535a80-1614-11eb-9e89-b3d692831c6b.png)

**Comment by MQuy** [comment]
can you send a screenshot if you run the command below 
```
cd src/kernel && make clean && make
```

**Comment by sxmxr** [comment]
@MQuy I compiled that command and here what I got :
![Screenshot from 2020-10-24 16-24-15](https://user-images.githubusercontent.com/47913479/97079940-73ed7c00-1615-11eb-9e51-585d47e40b4a.png)

**Comment by MQuy** [comment]
hum, what is your ubuntu version? my guess is the latest gcc have breaking changes, could you try with gcc 9.x

**Comment by sxmxr** [comment]
> hum, what is your ubuntu version? my guess is the latest gcc have breaking changes, could you try with gcc 9.x

@MQuy My ubuntu version is 20.04. So I have to make cross compiler again. Right?

**Comment by MQuy** [comment]
yes, try with gcc 9.x :)

**Comment by sxmxr** [comment]
> yes, try with gcc 9.x :)

Thank you, for your response. I'll get back to you in case of any queries.

**Comment by sxmxr** [comment]
@MQuy I have tried with gcc 9.3.0 and still getting same error.

**Comment by sxmxr** [comment]
![Screenshot from 2020-10-27 12-34-29](https://user-images.githubusercontent.com/47913479/97267800-c8307000-1850-11eb-85ae-135a42e0a833.png)
I'm getting this error while building toolchain.
I'm not able to find a patch file for newer version of gcc and of Binutils. Can you please help me to find that?
Binutils version : 2.34
GCC Version: 9.3.0

**Comment by sxmxr** [comment]
![Screenshot from 2020-10-27 14-58-25](https://user-images.githubusercontent.com/47913479/97282638-ea33ed80-1864-11eb-977d-c7fb43af6432.png)
I have installed gcc 9.1 cross compiler and tried to build file in toolchain but I'm getting this error while running this command "cd toolchain && ./build.sh"

**Comment by sxmxr** [comment]
@MQuy Ubuntu isn't working for me. So I am thinking to install Mac-OS on VirtualBox and will run it. Is it possible?

**Comment by MQuy** [comment]
can you give more details about the error above? I think Ubuntu is better in long term

**Comment by sxmxr** [comment]
@MQuy Here are the steps I have followed, Please correct me if I'm wrong :
1) Followed steps of https://wiki.osdev.org/GCC_Cross-Compiler and installed GCC 9.1.0 and Binutils 2.32, so basically activated new cross-compiler.
2) Downloaded the source code of mOS and moved to src directory. 
3) Then I entered this command "$ cd toolchain && ./build.sh"
4) After that I got the above error.

**Comment by MQuy** [comment]
could you try to open `build.sh` and modify these variables to fit in your case and run again?
```
PREFIX="$HOME/opt/cross"
TARGET=i386-mos
# SYSROOT cannot locate inside PREFIX
SYSROOT="$HOME/Projects/mos/src/toolchain/sysroot"
JOBCOUNT=$(nproc)
```

**Comment by sxmxr** [comment]
@MQuy Thank you for your response. Just to confirm, according to this (https://wiki.osdev.org/GCC_Cross-Compiler) my target variable will be TARGET=i686-elf. Right? or do I have to change target to i386-mos?
P.S. I have changed the SYSROOT.

**Comment by MQuy** [comment]
No, only SYSROOT, make sure that folder exist

**Comment by sxmxr** [comment]
@MQuy I made the required changes and compiled "./build.sh". Now I'm getting this error. Sorry for the inconvenience I have caused. I'm new to this type of
![Screenshot from 2020-10-28 23-06-56](https://user-images.githubusercontent.com/47913479/97474911-9dd6d380-1972-11eb-9e2b-eb448711a51f.png)
 field. :/

**Comment by sxmxr** [comment]
@MQuy Thank you for your help. ToolChain is compiled successfully. Now while compiling the "./create_image.sh" I'm getting this error.
![Screenshot from 2020-10-29 00-19-04](https://user-images.githubusercontent.com/47913479/97482748-93b9d280-197c-11eb-8e60-f939c99420dc.png)

**Comment by MQuy** [comment]
you should umount like this first
```
sudo umount /mnt/mos
sudo rm -rf /mnt/mos
```

**Comment by sxmxr** [comment]
> you should umount like this first
> 
> ```
> sudo umount /mnt/mos
> sudo rm -rf /mnt/mos
> ```

Yess.. I have
![Screenshot from 2020-10-29 00-31-01](https://user-images.githubusercontent.com/47913479/97483952-1ee79800-197e-11eb-85d1-816de090fb79.png)
 done the same but lead to this error :/

**Comment by MQuy** [comment]
can you comment this line from `./create_image.sh` and run it again
```
# cd ports/figlet && ./package.sh && cd ../..
```

**Comment by sxmxr** [comment]
@MQuy Sorry for the inconvenience I have caused. But I'm totally new to these topics and my faculty has given a project to implement a new feature in existing features. I'm planning to implement SMP and 2 level paging.

**Comment by MQuy** [comment]
no np, feel free to ask, I will answer when I am online ;)

**Comment by sxmxr** [comment]
![Screenshot from 2020-10-29 00-37-41](https://user-images.githubusercontent.com/47913479/97484636-fc09b380-197e-11eb-984f-195aea39392c.png)
After compiling "cd ports/figlet && ./package.sh && cd ../.."

**Comment by MQuy** [comment]
did you remove that line? you don't need that program to run

**Comment by sxmxr** [comment]
Yes, I commented it.
And here is the results.
1) After compiling "./create_image.sh"
![Screenshot from 2020-10-29 00-44-01](https://user-images.githubusercontent.com/47913479/97485300-f19be980-197f-11eb-97a1-7f110058a195.png)

2) After compiling "$ ./build.sh qemu iso"
![Screenshot from 2020-10-29 00-45-26](https://user-images.githubusercontent.com/47913479/97485367-0d06f480-1980-11eb-8f16-13914c750fe4.png)

**Comment by MQuy** [comment]
you don't have logs folder
```
$ cd src && mkdir logs
```

**Comment by sxmxr** [comment]
after creating it, I got a screen.
![Uploading Screenshot from 2020-10-29 00-48-33.png…]()

**Comment by sxmxr** [comment]
@MQuy After creating it, I run that again and I got this screen.
![Screenshot from 2020-10-29 00-48-33](https://user-images.githubusercontent.com/47913479/97485878-b8b04480-1980-11eb-877a-92b913962747.png)

**Comment by sxmxr** [comment]
![Screenshot from 2020-10-29 00-48-33](https://user-images.githubusercontent.com/47913479/97485945-cbc31480-1980-11eb-9965-8ef91c496e2e.png)

**Comment by MQuy** [comment]
can you open another terminal
```
$ cd src && gdb isodir/boot/mos.bin
``
in that gdb, type c and enter

**Comment by sxmxr** [comment]
![Screenshot from 2020-10-29 00-53-16](https://user-images.githubusercontent.com/47913479/97486220-25c3da00-1981-11eb-97a4-3de0532c4cdf.png)
Here's the output

**Comment by MQuy** [comment]
ops, I forget it should be
```
target remote localhost:1234
c
```

**Comment by sxmxr** [comment]
![Screenshot from 2020-10-29 00-55-24](https://user-images.githubusercontent.com/47913479/97486441-73404700-1981-11eb-89e7-b4b0abb6ace3.png)
Finallyyyyy!

**Comment by sxmxr** [comment]
So whenever I make changes, I have to run "$ ./build.sh qemu iso" , $ cd src && gdb isodir/boot/mos.bin, target remote localhost:1234, c" commands. Right?

**Comment by MQuy** [comment]
if you make changes to `src/apps` or `src/libraries` you have to run `./create_image.sh`

**Comment by sxmxr** [comment]
Ohh, Okay. Thank you so much @MQuy for your quick responses. Now I'll analyze the whole project, and will try to implement the capstones for the project.

**Comment by sxmxr** [comment]
Ohh, Okay. Thank you so much @MQuy for your quick responses. Now I'll analyze the whole project, and will try to implement the capstones for the project.
