### ISSUE TITLE
/bin/bash is not exist

### ISSUE THREAD

**Issue by sxmxr** [MQuy/mos#7]
I have installed the recent version of the mOS. It is showing this error. "/bin/bash is not exist". Is it in the development?
![image](https://user-images.githubusercontent.com/47913479/100994928-230a6500-357d-11eb-88a7-4d1119907b81.png)

**Comment by MQuy** [comment]
ah, I forget to note, you have to do following steps
```
cd src/ports/bash
./package.sh
```

```
cd src/ports/coreutils
./package.sh
```

**Comment by sxmxr** [comment]
After running this command, I got this:
![image](https://user-images.githubusercontent.com/47913479/100995726-2a7e3e00-357e-11eb-985a-df9c0b51a7ee.png)

**Comment by sxmxr** [comment]
> After running this command, I got this:
> ![image](https://user-images.githubusercontent.com/47913479/100995726-2a7e3e00-357e-11eb-985a-df9c0b51a7ee.png)

P.S.: I have already activated the cross-compiler

**Comment by MQuy** [comment]
I think you have to rename the cross-compiler in `package.sh` to your version

**Comment by sxmxr** [comment]
I changed the name of the cross-compiler to i686-elf-gcc, according to this
![image](https://user-images.githubusercontent.com/47913479/100996732-6bc31d80-357f-11eb-9ea2-5abc21938be4.png)
Now I'm getting this error : wchar.h: No such file or directory
![image](https://user-images.githubusercontent.com/47913479/100996834-8eedcd00-357f-11eb-8623-d65be8726202.png)

**Comment by sxmxr** [comment]
While compiling this: cd src/ports/coreutils
./package.sh
I don't know but somehow I'm getting this error. I think program isn't able to enter in the "if"
![image](https://user-images.githubusercontent.com/47913479/100999757-20ab0980-3583-11eb-8c16-d8c106b3a302.png)

**Comment by sxmxr** [comment]
> While compiling this: cd src/ports/coreutils
> ./package.sh
> I don't know but somehow I'm getting this error. I think program isn't able to enter in the "if"
> ![image](https://user-images.githubusercontent.com/47913479/100999757-20ab0980-3583-11eb-8c16-d8c106b3a302.png)

I have renamed the cross-compiler to i386-mos

**Comment by MQuy** [comment]
can you run this `echo $HOME` in your terminal to check the output? try removing `$HOME/coreutils-8.1` 🤔

**Comment by sxmxr** [comment]
![image](https://user-images.githubusercontent.com/47913479/101001772-9021f880-3585-11eb-84d4-aabfe8e06972.png)
Here it is.

**Comment by sxmxr** [comment]
I think I should change the path of this directory: COREUTILS_DIR to Current working directory?

**Comment by MQuy** [comment]
no, it has to be outside of `mos`, can you try removing that folder `$HOME/coreutils-8.1` and run `./package`

**Comment by sxmxr** [comment]
> no, it has to be outside of `mos`, can you try removing that folder `$HOME/coreutils-8.1` and run `./package`

I have done the same and got 2 errors :/ -->
![image](https://user-images.githubusercontent.com/47913479/101012917-87332600-3589-11eb-83df-6327936737ff.png)

**Comment by MQuy** [comment]
seem like you use the wrong cross-compiler tool, can you paste tool name here?

**Comment by sxmxr** [comment]
> seem like you use the wrong cross-compiler tool, can you paste tool name here?

Sorry, I don't know. How can I find the tool name?

**Comment by sxmxr** [comment]
> > seem like you use the wrong cross-compiler tool, can you paste tool name here?
> 
> Sorry, I don't know. How can I find the tool name?
Here's the cross-compiler version, I have been using
![image](https://user-images.githubusercontent.com/47913479/101014317-b34fa680-358b-11eb-8d2c-9124abc14d35.png)

**Comment by sxmxr** [comment]
**_Here is the SS of package.sh_**

![image](https://user-images.githubusercontent.com/47913479/101014436-e42fdb80-358b-11eb-8e58-4c2e0e50e747.png)

**Comment by MQuy** [comment]
you have to use `i386-mos-gcc`, I think you already installed `src/toolchain/build.sh`, right?

**Comment by sxmxr** [comment]
> you have to use `i386-mos-gcc`, I think you already installed `src/toolchain/build.sh`, right?

Yes yes, I have already installed but the target variable is i386-mos

**Comment by sxmxr** [comment]
> > you have to use `i386-mos-gcc`, I think you already installed `src/toolchain/build.sh`, right?
> 
> Yes yes, I have already installed but the target variable is i386-mos

![image](https://user-images.githubusercontent.com/47913479/101014877-8ea7fe80-358c-11eb-8b23-14790769a906.png)

**Comment by sxmxr** [comment]
> **_Here is the SS of package.sh_**
> 
> ![image](https://user-images.githubusercontent.com/47913479/101014436-e42fdb80-358b-11eb-8e58-4c2e0e50e747.png)

so, Where should I have to make changes in this package.sh file?

**Comment by MQuy** [comment]
could be the issue with naming of cross compiler in `src/toolchain/build.sh`, can you try changing `TARGET=i386-mos` -> `TARGET=i386-pc-mos` and running it again together without changing anything in `package.sh`

**Comment by sxmxr** [comment]
> could be the issue with naming of cross compiler in `src/toolchain/build.sh`, can you try changing `TARGET=i386-mos` -> `TARGET=i386-pc-mos` and running it again together without changing anything in `package.sh`

I have successfully executed both the commands but it's still showing the same error:
![image](https://user-images.githubusercontent.com/47913479/101018827-15aba580-3592-11eb-8d1d-0ca6115e669f.png)

**Comment by sxmxr** [comment]
> > could be the issue with naming of cross compiler in `src/toolchain/build.sh`, can you try changing `TARGET=i386-mos` -> `TARGET=i386-pc-mos` and running it again together without changing anything in `package.sh`
> 
> I have successfully executed both the commands but it's still showing the same error:
> ![image](https://user-images.githubusercontent.com/47913479/101018827-15aba580-3592-11eb-8d1d-0ca6115e669f.png)
These 2 are successfully executed and also ./build.sh from src folder along with ./create_image.sh
cd src/ports/bash
./package.sh
cd src/ports/coreutils
./package.sh

**Comment by MQuy** [comment]
can you check
```
cd src
debugfs hdd.img # enter new flow
cd bin
ls

```

**Comment by sxmxr** [comment]
It is showing this
![image](https://user-images.githubusercontent.com/47913479/101066418-61734480-35bc-11eb-8f80-19cd69527292.png)

**Comment by MQuy** [comment]
there is no bash there, something is wrong. when doing `cd src/ports/bash && ./package`, is there any error logs

**Comment by sxmxr** [comment]
Actually I didn't received any error. If you want to look at the output of the above command:
[terminal output.txt](https://github.com/MQuy/mos/files/5638271/terminal.output.txt)

**Comment by sxmxr** [comment]
> there is no bash there, something is wrong. when doing `cd src/ports/bash && ./package`, is there any error logs

I have tried again, but same issue is coming up. I am getting no errors while compiling ./package.sh in bash folder.

**Comment by sxmxr** [comment]
After re-running  toolchain and other file, I got this error while compiling the last step which is ./build.sh in src folder.
![image](https://user-images.githubusercontent.com/47913479/101140450-fddb2c80-3638-11eb-8849-0ba420e8601c.png)

**Comment by sxmxr** [comment]
> Actually I didn't received any error. If you want to look at the output of the above command:
> [terminal output.txt](https://github.com/MQuy/mos/files/5638271/terminal.output.txt)

@MQuy I have installed the cross-compiler using this target variable 
**export TARGET=i686-elf**
In the toolchain, ./build.sh has a target variable : **i386-pc-mos**
Is this a mistake here? or it's fine?

**Comment by MQuy** [comment]
Looking at your logs, I cannot spot any issues there. They should use different toolchain.
What are your variables
```
PREFIX="$HOME/opt/cross"
TARGET=i386-mos
# SYSROOT cannot locate inside PREFIX
SYSROOT="$HOME/Projects/mos/src/toolchain/sysroot" 
JOBCOUNT=$(nproc)
```
can you try commenting them out and do it again?

**Comment by sxmxr** [comment]
@MQuy  
These are my variables -->
PREFIX="$HOME/opt/cross"
TARGET=i386-pc-mos
SYSROOT="/home/sxmxr/OS_Project/mos/src/toolchain/sysroot"
JOBCOUNT=$(nproc)

**Comment by sxmxr** [comment]
> could be the issue with naming of cross compiler in `src/toolchain/build.sh`, can you try changing `TARGET=i386-mos` -> `TARGET=i386-pc-mos` and running it again together without changing anything in `package.sh`

after following this, I had changed the target variable.

**Comment by MQuy** [comment]
let remove those variables and run it again to see what happen 🤔

**Comment by sxmxr** [comment]
It is showing this.
![image](https://user-images.githubusercontent.com/47913479/101161487-dd21cf80-3656-11eb-954e-2fc66393b7df.png)

**Comment by MQuy** [comment]
no, not compiling toolchain, commenting out only for running for bash and coreutils

**Comment by sxmxr** [comment]
> no, not compiling toolchain, commenting out only for running for bash and coreutils

Sorry, @MQuy  but can you please suggest which line I have to comment and in which file. I'm lit bit confused.

**Comment by MQuy** [comment]
My suggested follow is like below
1. revert env variables back
2. compile toolchain
3. comment en variables
4. `cd src/ports/bash && ./package.sh`
5. `cd src/ports/coreutils && ./package.sh`

**Comment by sxmxr** [comment]
> My suggested follow is like below
> 
> 1. revert env variables back
> 2. compile toolchain
> 3. comment en variables
> 4. `cd src/ports/bash && ./package.sh`
> 5. `cd src/ports/coreutils && ./package.sh`

ohh okayy Got it. I'm on it.

**Comment by sxmxr** [comment]
@MQuy I have done the same and didn't get any errors. Should I run ./create_image.sh & ./build.sh?

**Comment by MQuy** [comment]
ah, could be the issue of order
1. `cd src`
1. `./create_image.sh`
2. `cd src/ports/bash && ./package.sh`
3. `cd src/ports/coreutils && ./package.sh`
4. `./build.sh qemu iso`

**Comment by sxmxr** [comment]
Yesss Now, it working completely perfectt.
![Capture23](https://user-images.githubusercontent.com/47913479/101178971-a310f780-366f-11eb-8139-444ea1437b8b.PNG)

**Comment by MQuy** [comment]
could you create a pr to update README.md :D

**Comment by sxmxr** [comment]
I just had one query that in the older version of the mOS, 
![image](https://user-images.githubusercontent.com/47913479/101179613-7a3d3200-3670-11eb-82d5-2d0f261b90fe.png)
 Here there were few folders of commands like uname, pwd, ls commands. Where are they commands in the new version of the OS. I'm unable to find it.

**Comment by MQuy** [comment]
they are part of coreutils, more details https://github.com/coreutils/coreutils

**Comment by sxmxr** [comment]
Oh Okayy Thank you. :) Sure I'll create a PR to update README.md by tonight :D
